### ISSUE TITLE
Untangle Forum Links 

### ISSUE THREAD

**Issue by Deverall** [willquill/untangle-mdns#2]
The untangle forum links do not redirect or appear to be valid. It's difficult to try and accomplish what you have done without all the info.

**Comment by willquill** [comment]
Thanks for pointing that out! Fixed in [this PR](https://github.com/willquill/untangle-mdns/pull/3), which has been merged.

This is the link you're looking for: https://forums.edge.arista.com/forum/community-contribution/hacks/36649-mdns-external
